### ISSUE TITLE
Add support for multiple profiles per user

### ISSUE THREAD

**Issue by archishou** [AndyGrant/OpenBench#123]
Currently, A user who would like to work on multiple users, must manually change the requires source and engine name when switching between engines. A nice quality of life feature would be making it such that when creating a test, selecting an engine would automatically tied to your desired source.

This was also briefly discussed on discord.

**Comment by AndyGrant** [comment]
Three options I see. All options require changing the models from a CharField to a JSON field, which will be a dict of ``engine-name : source-repo``. I do not feel like writing a custom migration for this, since when we go from master to development that database is going to need big changes. So I'll be clearing the default engines most likely, which will give users a chance to see the new interface for setting multiple repos.

1. Suppose your default engine is Ethereal, and the repo is AndyGrant/Ethereal. Any time you save/update your profile, it will take the set default and set repo, and then place them into the dictionary of repos. This means if you were to swap your engine, save, and then swap your repo, save, you would be confused.

2. Same as the above, but once you've introduced a 2nd engine to the pair, future attempts to look at your profile will show the additional fields. 

3. Remove the repo field from the profile page. Add a settings page. This settings page is for individual profiles. It will have a form entry for _every_ engine on the framework. You can set the engines there. This might also be used for future user-specific-but-not-engine-specific settings.

**Comment by archishou** [comment]
Hm, in my opinion, both options seems a little convoluted if I understand them correctly. What are you're thoughts on keeping the existing profile page but having an 'Add Engine' button in your profile. This will then allow you to setup an engine with your own source. Then you can use a check-mark or some other type of button next to each row of engine to pick a default.

**Comment by AndyGrant** [comment]
Yeah this is good. Its in the pipeline.

**Comment by AndyGrant** [comment]
![image](https://github.com/AndyGrant/OpenBench/assets/11588594/a3a62c76-d4e0-4676-8f7e-ca0f2a56ca91)

**Comment by archishou** [comment]
This is awesome! So nice to see a sketch and the CSS so soon after suggesting it :)

**Comment by AndyGrant** [comment]
Resolved in https://github.com/AndyGrant/OpenBench/pull/125

![image](https://github.com/AndyGrant/OpenBench/assets/11588594/fc8df5c8-202b-457e-99dc-0bea28d31380)
