### ISSUE TITLE
Is it possible to download the games from openbench?

### ISSUE THREAD

**Issue by Matuiss2** [AndyGrant/OpenBench#33]
Like it can be done with fishtest? If yes, how?

**Comment by AndyGrant** [comment]
Unfortunately, no. I have tried to limit bandwidth usage, since the majority of games have been played by Noobpwn, and I want to limit his costs, since he has already been so generous.
However, I at one point modified my own client to save the games. I imagine the pgn file has a few hundred thousand to a million games. I could share this on dropbox and leave a link here for you if you are interested. If you are just looking for raw games, and not to grab games from specific tests, that may do the trick for you.
I will note that my pgn does contain some games from Laser, but they are a tiny percentage.

**Comment by Matuiss2** [comment]
That would be great if you shared it, thank you!

**Comment by AndyGrant** [comment]
I had saved two seperate PGNS (at some point I started writing to a new file, nothing of importance). I've uploaded a zipped folder of them to dropbox. The link is below, and the size is just under 1GB.

https://www.dropbox.com/s/x5owjdzou2xuw75/OpenBenchPGNS.zip?dl=0

Let me know if there are any issues.
