### ISSUE TITLE
No workloads for us but a test is pending

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#36]
I am now able to run and debug the client. I'm facing this

```
<Warning> Server has no workloads for us
```
But a test is pending. Any clue ?

**Comment by AndyGrant** [comment]
A test must be approved before it can be run. This is to prevent tests containing bad code from being run. If you said yourself to be a superuser, you should be able to approve your own test by clicking on it and clicking the "approve" button. If you did not set yourself to be a superuser, you should go do that now. OpenBench uses "cross-approval", ie someone else has to approve your test. However, you can bypass that as a super user, which you'll want since its you working on the engine, not a team of 100 people like Fishtest.

**Comment by tryingsomestuff** [comment]
ok thank, sorry for the stupid questions ;-)
I'd really like to make this work, seems to be such a great framework.
