### ISSUE TITLE
Some possible genericity 

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#37]
To make OpenBench even more easy to use for other engine I can spot a few simple modifications :

- make build command custom (not make, but a user command)
- do not depend on a '/src' directory, stay on root directory of the repo, the custom command can cd where it wantsto
- possible configuration of own cutechess bin dir

**Comment by tryingsomestuff** [comment]
Another fun thing may be to be able to copy additional files to the Engines directory. Maybe this requires to use a hashed directory, instead of a hashed exe name, so that the files (and the engine) are just copied to the hashed directory. This way engines depending on some others files may be tested also.

**Comment by AndyGrant** [comment]
Why do you need additional files?

**Comment by tryingsomestuff** [comment]
Minic case is not very relevant here probably, I am not exposing all parameter through command line or xboard/uci options and sometimes use a json configuration file. But I think of others engines with specific files also like learning file, own book, tables on disk, ...

**Comment by lucasart** [comment]
> To make OpenBench even more easy to use for other engine I can spot a few simple modifications :
> 
> * make build command custom (not make, but a user command)
> * do not depend on a '/src' directory, stay on root directory of the repo, the custom command can cd where it wantsto
> * possible configuration of own cutechess bin dir

Agreed on the first 2 points.

For the 3rd, I don't think this is a good idea. We want to make sure that all clients are running exactly the same way, same cutechess executable (and library). Otherwise it's not possible to remotely assist people. Who knows what user xyz has done, miscompiled cutechess, used a newer or older version that isn't compatible, etc.

**Comment by AndyGrant** [comment]
Suggestion 1 is apart of the new client as is. For example, Lucas can add "pext" to the custom flags for Ethereal if he wants a faster compile when completing workloads for Ethereal.

Suggestion 2 is dependent on suggestion 1, and it is something I am going to do right now, assuming its as trivial as it appears.

Suggestion 3 I also disagree with. In another issue Lucas said something like "We want to lower the barrier of entry for donating CPU time". Having to support multiple cutechess versions sounds problematic. We already ran into an issue over Qt versions.

Also, Lucas, in case git's @ feature does not do what I expect, I opened an issue here for Demolito support, asking you for timecontrol/hash/thread settings for STC/LTC and SMP STC/LTC.

**Comment by lucasart** [comment]
@AndyGrant: For the new client, it's 'dev' for Demolito (and 'pext' for Ethereal). This is a 10% speed-up on my machine, 8% from clang (vs. gcc), and 2% from pext.
```
COMPILATION_FLAGS = {
    'ETHEREAL' : ['pext'],   # Custom makefile flags for Ethereal
    'LASER'    : [],   # Custom makefile flags for Laser
    'WEISS'    : [],   # Custom makefile flags for Weiss
    'DEMOLITO' : ['dev'],   # Custom makefile flags for Demolito
};
```

**Comment by lucasart** [comment]
@AndyGrant: Actually, there's an even better solution. GCC and Clang define `__BMI2__` when available, so no need to define it by hand from the makefile, instead all the makefile provides is the `-m*` parameters (eg. march=native, or mpopcnt, or mbmi2 etc.). and voila. So no custom makefile flags will be needed for Demolito, both popcnt and pext will be auto-detected.

**Comment by AndyGrant** [comment]
@lucasart: You overlooked the Ryzen case. If you take a look at http://chess.grantnet.us/machines/ you'll see that most machines are running much slower. My machine on OpenBench is a Ryzen 1950x, and so are Noobpwnftw's. This is one of the motivations for the new client, so people like you, who ( I think ) are running Intel processors, can just add a PEXT flag to the ``COMPILATION_FLAGS``

**Comment by lucasart** [comment]
Thanks! I didn't know that. I wonder why AMD would release new hardware instructions that are even slower than their software emulated equivalent (magic), but anyway it's life.

Existing tests are running and of course the makefile can't be changed mid-flight. But the new master for Demolito should fix the problem. Now the makefile can be used as follows:
* default: `make` (PEXT is off and GCC is used)
* clang (for you): `make CC=clang` (8% faster on my machine, your mileage may vary, but I expect it will be faster for you too). I didn't make this the default, because the documentation for OpenBench requires workers to install gcc, not clang, so I can't assume that workers have clang.
* clang and pext (for me): `make CC=clang pext`.

**Comment by AndyGrant** [comment]
I believe I have pushed support for everything I felt worth doing thus far in this thread -- Client provides option for a custom make directory, Client provides option for a custom build script. I will be swapping my worker to a clang build if it is faster using this method for Demolito.

**Comment by tryingsomestuff** [comment]
thanks ;)
