### ISSUE TITLE
Isn't priority redundant with throughput ?

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/OpenBench#41]
I think priority can be removed, and throughput can be used instead. Example:
* default: all tests use normal 1000 throughput.
* to put a test in front of all others, instead of setting priority=1, one can simply set throughput to zero for all other tests. At least it makes the intention clear. Of course, this is an anti-social behavior to begin with, but that's a different discussion.
* to put a test behind all others, instead of setting priority=-1, one can simply set throughput to zero for the test.

PS: The reason why Fishtest has both priority and throughput is historical. Priority was available first, and throughput was invented later.

**Comment by AndyGrant** [comment]
No, it is not. The classic use case from Fishtest is people who run Speculative LTC's setting their throughput to 166, in order to not take up too many resources for an "undeserved" LTC. Plus, suppose there are 20 tests on the framework (although thats uncommon now, I used to have 50 tests up there at a time when Noob had 150 machines on the framework). Would you rather set 49 tests to throughput 0, or set 1 test to prio 1?
