### ISSUE TITLE
Admin login fails

### ISSUE THREAD

**Issue by jdart1** [AndyGrant/OpenBench#54]
With the current source, after doing the recommended setup steps for the server in README.md, I am getting this exception after logging in as admin:

Request Method: | GET
-- | --
http://192.168.0.71:8000/
2.0.6
OperationalError
no such column: OpenBench_profile.engine
/home/jdart/.local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 303
/usr/bin/python3
3.6.9
['/home/jdart/chess/OpenBench',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/jdart/.local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Sat, 22 Feb 2020 18:13:42 +0000

**Comment by AndyGrant** [comment]
This is due to an oversight on my part. I thought I tried to mention it in the readme, but I may have failed. 

The admin account is only able to be used to view the admin interface, /admin. It is not a "normal" user, and cannot see the home page. I will remedy this when I get home by not allowing logins and asking the user to create a normal account. You can fix it on your end by creating anormal account through the interface, not the command line. 

Long answer: website users, the ones that can create and contribute to testing, are an extension of the base user, which is what you created from the command line.

**Comment by AndyGrant** [comment]
Resolved: https://github.com/AndyGrant/OpenBench/commit/e6348916e284743006b91051e16e353f1a76c260
